### ISSUE TITLE
type LatLngExpression not found

### ISSUE THREAD

**Issue by mcallisto** [mcallisto/scalajs-leaflet#2]
Once solved #1, the first of several errors arises:

[Error:(45, 36)](https://github.com/mcallisto/scalajs-leaflet/blob/1ceca905345df967015765ada8f19a440685b36b/src/main/scala/vision/id/leaflet/Leaflet.scala#L45)
```
not found: type LatLngExpression
      def isFlat(latlngs: js.Array[LatLngExpression]): Boolean = js.native
```

Type `LatLngExpression` is defined at [Leaflet.scala#L1650](https://github.com/mcallisto/scalajs-leaflet/blob/1ceca905345df967015765ada8f19a440685b36b/src/main/scala/vision/id/leaflet/Leaflet.scala#L1650)

**Comment by coreyauger** [comment]
Ok.  Mine is compiling fine.. so not sure what is going on yet.  Looking at this however we have `LatLngExpression` defined as a union type. 
We can find some discussion of this here: https://github.com/scala-js/scala-js/issues/1824

If we fail to get the type union to work.. we can fall back to declaring  `LatLngExpression` as a trait that the other objects extend.

But lets get it so that our compile behaviours is the save first ;)

**Comment by mcallisto** [comment]
How did you solve #1? Maybe mine is not compiling because of that...
